### PR TITLE
Create PowerShell install script

### PR DESCRIPTION
**Pull request by sitiom**
I would like to have a quick way to install my dotfiles in Windows without needing MSYS2 or Git Bash. This would prove quite useful.

### CODE REVIEW

**Comment by sitiom** [comment]
Here's a simple uninstall script for PowerShell that only depends on [powershell-yaml](https://github.com/cloudbase/powershell-yaml).

```ps1
$CONFIG = "install-windows.conf.yaml"

$confObj = ConvertFrom-Yaml ([string](Get-Content $CONFIG -Raw))
foreach ($target in ($confObj | Where-Object Keys -eq link).Values.Keys) {
    if ((Test-Path $target) -and (Get-Item $target).Attributes -match "ReparsePoint") {
        Write-Host "Removing $target" -ForegroundColor Red
        Remove-Item $target
    }
}
```

**Comment by sitiom** [comment]
Here's a simple uninstall script for PowerShell that only depends on [powershell-yaml](https://github.com/cloudbase/powershell-yaml).

```ps1
$CONFIG = "install.conf.yaml"

$confObj = ConvertFrom-Yaml ([string](Get-Content $CONFIG -Raw))
foreach ($target in ($confObj | Where-Object Keys -eq link).Values.Keys) {
    if ((Test-Path $target) -and (Get-Item $target).Attributes -match "ReparsePoint") {
        Write-Host "Removing $target" -ForegroundColor Red
        Remove-Item $target
    }
}
```

**Comment by sitiom** [comment]
Here's a simple uninstall script for PowerShell that only depends on [powershell-yaml](https://github.com/cloudbase/powershell-yaml).

```ps1
$CONFIG = "install.conf.yaml"

$confObj = ConvertFrom-Yaml ([string](Get-Content $CONFIG -Raw))
foreach ($target in ($confObj | Where-Object Keys -eq link).Values.Keys) {
    if ((Get-Item $target -Force -ErrorAction SilentlyContinue).LinkType -eq "SymbolicLink") {
        Write-Host "Removing $target" -ForegroundColor Red
        Remove-Item $target
    }
}
```

**Comment by anishathalye** [comment]
This looks interesting, thanks for the pull request! It might be a little bit of time until I can review it. I think it might be neat to include it in [Dotbot](https://github.com/anishathalye/dotbot) as well (rather than just this dotfiles template).

I don't want to include an uninstall script (because in general, an arbitrary install can't be un-done effectively) along with Dotbot, but there's one available in the [wiki](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#uninstall-script) for people who want it. You could add your PowerShell version there.

**Comment by sitiom** [comment]
> I don't want to include an uninstall script (because in general, an arbitrary install can't be un-done effectively) along with Dotbot, but there's one available in the [wiki](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#uninstall-script) for people who want it. You could add your PowerShell version there.

Alright, added it to the wiki

**Comment by anishathalye** [comment]
Squashed/merged!

**Pull request closed without merging**
